FROM node:18-alpine

# 필수 패키지 업데이트 및 설치
#RUN apt-get update && apt-get install -y npm
RUN apk update && apk add --no-cache bash

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000
